### ISSUE TITLE
Wrong Device Status : SW=6930 (EXPECT=9000, MASK=FFFF

### ISSUE THREAD

**Issue by cryptowalletsolution** [LedgerHQ/ledger-app-monero#43]
Hello Community.

I created a Monero wallet back on Jan 2018 using Ledger Nano S.   I put XMR - Monero into that wallet.  And now for some reason when I try to login and after entering my password, the screen or wallet flickers and reverts back to the page to enter my password.   I even tried using Ledger Nano X too and still the same thing happens.   

Also downloaded the Monero desktop  wallet Current Version: 0.14.1.0 Boron Butterfly, the same happens.  

So I decided to restore the Monero Wallet using Ledger S and I get the following errors.

 failed to generate new wallet: Wrong Device Status : SW=6930 (EXPECT=9000, MASK=FFFF 
 failed to generate new wallet: Unable to enumerate device 114115:11415: NULL Device 

Please advise.    Thank you.     I have Windows 10 Home Edition.

P.S. I went online and saw that we can use CLI and Docker and all that stuff however I am not computer savvy enough to use those methods and don't want to break or corrupt the wallet and not be able to access my Monero at all.

P.P.S. I read many posts and followed all the instructions such as Running as Administrator, making sure the Monero app is running on the Ledger first, switching cables from the front ports of the computer to the rear ports, reversing the order of connecting the cable, tried using Monerujo on the phone with the right Restore Height  etc. etc. and nothing.  Whew!

**Comment by cslashm** [comment]
Please provide:
 -OS type and version (win7, win10, linux.., mac...)
- Firmware version of NanoS
- Application version of  MoneroApp on Ledger


Moreover I do not understand how you can get a 6930 from the device if the device is not enumerated (ie not seen)

**Comment by patboy3** [comment]
I have the same problem and nothing work.
- Win 10
- 1.5.5
- 1.3.1
- Current Version: 0.14.1.2 Boron Butterfly

Error: failed to load wallet: Wrong Device Status : SW=6930 (EXPECT=9000, MASK=ffff)

**Comment by cslashm** [comment]
Ok I see.
App need upgrade to allow 0.14.1.2 client
It will be released next week

**Comment by dEBRUYNE-1** [comment]
>App need upgrade to allow 0.14.1.2 client

Does v1.3.1 still work with v0.14.1.0?

**Comment by cslashm** [comment]
yes 1.3.1 is locked to 0.14.1.0. 

(Because of last bug-fail with lost&recovery funds, now app is locked on test version)
I lock on full version, may be I can lock on M.m.µ, and ignore last *pico* revision number. No?

**Comment by remon-nashid** [comment]
Any updates?

**Comment by patboy3** [comment]
No news about that ?

**Comment by pricead** [comment]
@patboy3 have you tried downloading the updated Monero app for Ledger? You need to enable Developer Settings in Ledger Live to find it.

**Comment by patboy3** [comment]
Ok i will try that thx. For the moment i use the 0.14.1.0 for the cli and it work. I was juste asking myself what was the resolution of this problem. Have a nice day and thx for all

**Comment by Jaekr** [comment]
Exactly the same problem here (see here for the Monero wallet gui issue https://github.com/monero-project/monero-gui/issues/2480 )

**Comment by cslashm** [comment]
6930 means Client version not supported by app. 
Update the app or wait for incoming release.

**Comment by Soliver84** [comment]
Hello I have Ledger Nano S,

I have saved myself extra monero-gui-v0.13.0.4 because it also contains my DATA and my 2.4Monero, in the new version it is displayed with 0 Monero. I had that before and got the old one working again and lo and behold my monero were there.

You have changed the database, can I convert the old database?

Please help me I want my MONERO again.

My data:
Ledger Nano S firmware: 1.60
MONERO app on the ledger: 1.4.2
monero-gui-v0.13.0.4

Error:
Wallet could not be opened: Wrong Device Status: SW = 6930 (EXPECT = 9000, MASK = ffff)

How do I get my Monero?

**Comment by pricead** [comment]
You can't use old versions of the Monero GUI/CLI. Monero has forked since those versions were current and the old blockchain died. Your coins will be available on the new blockchain that 0.15.0.2 is compatible with. You need to have 0.15.0.2 to use with the Ledger Monero app as well, otherwise you'll get the "Wrong Device Status" error you've see.

I suggest downloading the 0.15.0.2 GUI, and re-adding your Ledger wallet there instead of opening your old wallet file in case it was corrupted. Make sure when adding the wallet that you pick a blockchain height for a date that came before your first transaction, so it will discover all of your coins.

**Comment by Soliver84** [comment]
I did it but now have other problems:
yes i have 0.15.0.2 have a prolem:
https://github.com/LedgerHQ/ledger-app-monero/issues/51

**Comment by ambam0123** [comment]
hey guys, i still have this problem, 
using: win 10, Ledger nano s (firmware 1.5.5.), monero gui 15.0.4, Monero app 1.3.1

any advice would be greatly appreciated

**Comment by cslashm** [comment]
@ambam0123 monero app 1.3.1 is fully "out-of-date".

Please upgrade your NanoS and your application

**Comment by ambam0123** [comment]
Thanks a million! i had done that, but my ledger live software was out of date too. I had to update the ledger live software first, in order to update the ledger nano s Firmware and then the monero app. just in case someone else runs into the same problem in the future.

**Comment by Just-27** [comment]
hello I have a problem ho I can update the Monero Gui wallet on macos Catalina. to the lates Update Maybe im stupid or its to complicated for me jet 🙃

**Comment by pricead** [comment]
> hello I have a problem ho I can update the Monero Gui wallet on macos Catalina. to the lates Update Maybe im stupid or its to complicated for me jet 🙃

This is really the wrong place to post that kind of problem (I suggest http://reddit.com/r/monerosupport), but you likely just need to download and install the newest Monero GUI from https://www.getmonero.org/downloads/
